spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.redisson.spring.starter.RedissonAutoConfiguration

# for starting out the database only but once teh database is up and running (there is no need for the follwoing lines)
#spring:
#  profiles.include: changlog
#  liquibase:
#    change-log: classpath:db/changelog/changelog-schema-mysql.xml
#    drop-first: true
