spring:
  profiles.include: changlog
  liquibase:
    change-log: classpath:db/changelog/changelog-schema-mysql.xml
    drop-first: true


logging:
  level:
    liquibase: INFO
    org:
      springframework:
        cache: INFO
