spring:
  liquibase:
    change-log: classpath:db/changelog/changelog-schema-test.xml

#    I can choose between sql or xml schema:
#       db/changelog/sample-data.xml
#       db/changelog/changelog-schema-test.xml


#You can set spring.jpa.hibernate.ddl-auto explicitly and the standard Hibernate property values are none, validate, update, create-drop.
#Spring Boot chooses a default value for you based on whether it thinks your database is embedded (default create-drop) or not (default none).
#An embedded database is detected by looking at the Connection type: hsqldb, h2 and derby are embedded,
