export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_CACHE_MACHINES = 'GET_CACHE_MACHINES';
export const GET_CACHE_OPERATIONS = 'GET_CACHE_OPERATIONS';
export const GET_CACHE_MACHINE_OPERATIONS = 'GET_CACHE_MACHINE_OPERATIONS';
export const GET_CACHE_MATERIALS = 'GET_CACHE_MATERIALS';
export const GET_CACHE_LOCATIONS = 'GET_CACHE_LOCATIONS';

export const GET_SQL_MATERIALS = 'GET_SQL_MATERIALS';
export const GET_SQL_LOCATIONS = 'GET_SQL_LOCATIONS';
export const GET_SQL_PRODUCTION_ORDER = 'GET_SQL_PRODUCTION_ORDER';

export const CREATE_MACHINE = 'CREATE_MACHINE';
export const CREATE_OPERATION = 'CREATE_OPERATION';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const CREATE_MATERIAL = 'CREATE_MATERIAL';
export const CREATE_PRODUCTION_ORDER = 'CREATE_MATERIAL';
