export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_CACHE_MACHINES = 'GET_CACHE_MACHINES';
export const MACHINE_CACHE_ERROR = 'MACHINE_CACHE_ERROR';
export const GET_CACHE_OPERATIONS = 'GET_CACHE_OPERATIONS';
export const OPERATION_CACHE_ERROR = 'OPERATION_CACHE_ERROR';
export const GET_CACHE_MACHINE_OPERATIONS = 'GET_CACHE_MACHINE_OPERATIONS';
export const MACHINE_OPERATIONS_CACHE_ERROR = 'MACHINE_OPERATIONS_CACHE_ERROR';
export const GET_CACHE_MATERIALS = 'GET_CACHE_MATERIALS';
export const MATERIALS_CACHE_ERROR = 'MATERIALS_CACHE_ERROR';
export const GET_CACHE_LOCATIONS = 'GET_CACHE_LOCATIONS';
export const LOCATIONS_CACHE_ERROR = 'LOCATIONS_CACHE_ERROR';

export const GET_SQL_MORS = 'GET_SQL_MORS';
export const SQL_MORS_ERROR = 'SQL_MORS_ERROR';
export const GET_SQL_MATERIALS = 'GET_SQL_MATERIALS';
export const SQL_MATERIALS_ERROR = 'SQL_MATERIALS_ERROR';
export const GET_SQL_LOCATIONS = 'GET_SQL_LOCATIONS';
export const SQL_LOCATIONS_ERROR = 'SQL_LOCATIONS_ERROR';
export const GET_SQL_PRODUCTION_ORDER = 'GET_SQL_PRODUCTION_ORDER';
export const SQL_PRODUCTION_ORDER_ERROR = 'SQL_PRODUCTION_ORDER_ERROR';

export const CREATE_MACHINE = 'CREATE_MACHINE';
export const CREATE_OPERATION = 'CREATE_OPERATION';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const CREATE_MATERIAL = 'CREATE_MATERIAL';
export const CREATE_PRODUCTION_ORDER = 'CREATE_MATERIAL';

export const SQL_ERROR = 'SQL_ERROR';

export const CHANGE_OPERATION_STATUS = 'CHANGE_OPERATION_STATUS';
export const LINK_MACHINE_OPERATION = 'LINK_MACHINE_OPERATION';
export const UNLINK_MACHINE_OPERATION = 'UNLINK_MACHINE_OPERATION';
